project:
  type: website
  output-dir: docs
  
website:
  title: "About Myself"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Hobbies"
        href: Hobby.qmd
      - text: "Travel"
        href: travel.qmd
      - text: "Reflection"
        href: Reflection.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



